name: download_release_qgis

on:
  workflow_dispatch:

env:
  LR: release-3_12
  LTR: release-3_10
  
jobs:
  OSGeo4W:
    strategy:
      max-parallel: 4
    runs-on: windows-2019
    timeout-minutes: 360
    
    env:
      OSGEO4W_ROOT: C:\OSGeo4W64
      OSGEO4W_ARCH: x86_64
      CLCACHE_DIR: c:\clcache-x86_64
      PLATFORM: x64
      
    steps:
    - name: Download qgis
      run: curl --output c:/QGIS-OSGeo4W-3.34.7-2.msi https://download.qgis.org/downloads/QGIS-OSGeo4W-3.34.7-2.msi
      
    - name: set release date
      run: |
        echo "RELEASE_DATE=$(date +%Y%m%d-%H%M%s)" >> ${GITHUB_ENV}
      shell: bash

    - name: Release qgis
      uses: softprops/action-gh-release@v2
      with:
        name: QGIS-OSGeo4W-3.34.7-2.msi
        tag_name: ${{ env.RELEASE_DATE }}
        files: c:/QGIS-OSGeo4W-3.34.7-2.msi
                    
