name: find-vs-windows

on:
  workflow_dispatch:

env:
  LR: release-3_12
  LTR: release-3_10
  
jobs:
  FindVs:
    strategy:
      max-parallel: 4
    runs-on: windows-2019
    timeout-minutes: 360
    
    env:
      OSGEO4W_ROOT: C:\OSGeo4W64
      OSGEO4W_ARCH: x86_64
      CLCACHE_DIR: c:\clcache-x86_64
      PLATFORM: x64
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
        
    - name: run bat
      shell: cmd
      run: |
        ./ms-windows/osgeo4w/_findvscl.cmd
                    
