name: Download QGIS By Flatpak

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: install flatpak
        run: |
          echo "install flatpak:"
          sudo apt update
          sudo apt install flatpak zip
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak --version

      - name: install flatpak QGIS
        run: |
          echo "install QGIS:"
          sudo flatpak install -y flathub app/org.qgis.qgis/x86_64/stable
          sudo flatpak info org.qgis.qgis
          sudo flatpak info org.qgis.qgis --show-runtime
          sudo ls -l /var/lib/flatpak/app/org.qgis.qgis/ 2>/dev/null || echo "not exists"
          sudo ls -l /var/lib/flatpak/runtime/ 2>/dev/null || echo "not exists"
          sudo ls -l /var/lib/flatpak/exports/share/applications/ 2>/dev/null || echo "not exists"

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date +%Y%m%d-%H%M%s)" >> ${GITHUB_ENV}
        shell: bash

      - name: pack flatpak app
        run: |
          zip -r flatpak-qgis-app.zip /var/lib/flatpak/app/org.qgis.qgis/current
          zip -r flatpak-qgis-rt.zip /var/lib/flatpak/runtime/org.kde.Platform

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: flatpak-qgis-${{ env.RELEASE_DATE }}
          name: flatpak-qgis-${{ env.RELEASE_DATE }}
          body: https://qgis.org/resources/installation-guide/#flatpak
          files: |
            flatpak-qgis-app.zip
            flatpak-qgis-rt.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}