name: Download QGIS By Flatpak

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y flatpak zip git python3-pip
          # 安装 flatpak2appdir
          pip3 install flatpak2appdir
          flatpak2appdir --version

      - name: Add flathub remote
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Install QGIS flatpak
        run: |
          sudo flatpak install -y flathub app/org.qgis.qgis/x86_64/stable
          sudo flatpak list | grep qgis

      - name: Export to AppDir with flatpak2appdir
        run: |
          # 导出为标准 AppDir
          flatpak2appdir org.qgis.qgis --output QGIS.AppDir
          ls -la QGIS.AppDir/

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date +%Y%m%d-%H%M%S)" >> ${GITHUB_ENV}

      - name: Pack AppDir to zip
        run: |
          zip -r -y QGIS-AppDir-${{ env.RELEASE_DATE }}.zip QGIS.AppDir

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: flatpak-qgis-appdir-${{ env.RELEASE_DATE }}
          name: flatpak-qgis-appdir-${{ env.RELEASE_DATE }}
          body: |
            QGIS Flatpak 导出标准 AppDir 离线包
            https://qgis.org/resources/installation-guide/#flatpak
          files: |
            QGIS-AppDir-${{ env.RELEASE_DATE }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
