name: build-on-windows

on:
  workflow_dispatch:

env:
  LR: release-3_12
  LTR: release-3_10
  
jobs:
  OSGeo4W:
    strategy:
      max-parallel: 4
    runs-on: windows-2019
    timeout-minutes: 360
    
    env:
      CC: C:\OSGeo4W64\bin\clcache.bat
      CXX: C:\OSGeo4W64\bin\clcache.bat
      OSGEO4W_ROOT: C:\OSGeo4W64
      OSGEO4W_ARCH: x86_64
      CLCACHE_DIR: c:\clcache-x86_64
      PLATFORM: x64
      
    steps:
    - name: Checkout QGIS repo
      uses: actions/checkout@v4
      with:
        repository: qgis/QGIS

    - name: Setup build variables
      run: |
        branch=${{ github.ref_name }}
        BUILD_SOURCEVERSION=${{ github.sha }}

        echo "BRANCH: ${branch}"
        echo "BUILD_SOURCEVERSION: ${BUILD_SOURCEVERSION}"
        echo "LR: ${LR}"
        echo "LTR: ${LTR}"

        case "${branch}" in
        "${LTR}")
          OSGEO4W_PKG=qgis-ltr-dev
          OSGEO4W_DEPS=qgis-ltr-dev-deps
          ;;
        "${LR}")
          OSGEO4W_PKG=qgis-rel-dev
          OSGEO4W_DEPS=qgis-rel-dev-deps
          ;;
        *)
          OSGEO4W_PKG=qgis-dev
          OSGEO4W_DEPS=qgis-dev-deps
          ;;
        esac

        target=Experimental
        major=$(sed -ne 's/^SET(CPACK_PACKAGE_VERSION_MAJOR "\([0-9]*\)")\s*$/\1/ip' CMakeLists.txt)
        minor=$(sed -ne 's/^SET(CPACK_PACKAGE_VERSION_MINOR "\([0-9]*\)")\s*$/\1/ip' CMakeLists.txt)
        patch=$(sed -ne 's/^SET(CPACK_PACKAGE_VERSION_PATCH "\([0-9]*\)")\s*$/\1/ip' CMakeLists.txt)
        binary=${{ github.run_number }}

        version=$major.$minor.$patch
        sha="${BUILD_SOURCEVERSION:0:10}"

        buildname="$OSGEO4W_PKG-$version-$sha-$target-VC14-$OSGEO4W_ARCH"

        echo "TARGET=$target" >> ${GITHUB_ENV}
        echo "OSGEO4W_PKG=$OSGEO4W_PKG" >> ${GITHUB_ENV}
        echo "OSGEO4W_DEPS=$OSGEO4W_DEPS" >> ${GITHUB_ENV}
        echo "MAJOR=$major" >> ${GITHUB_ENV}
        echo "MINOR=$minor" >> ${GITHUB_ENV}
        echo "PATCH=$patch" >> ${GITHUB_ENV}
        echo "BINARY=$binary" >> ${GITHUB_ENV}
        echo "VERSION=$version" >> ${GITHUB_ENV}
        echo "BUILDNAME=$buildname" >> ${GITHUB_ENV}
        echo "BUILD_SHA=$sha" >> ${GITHUB_ENV}
        
        echo "TARGET: $target"
        echo "OSGEO4W_PKG: $OSGEO4W_PKG"
        echo "OSGEO4W_DEPS: $OSGEO4W_DEPS"
        echo "MAJOR: $major"
        echo "MINOR: $minor"
        echo "PATCH: $patch"
        echo "BINARY: $binary"
        echo "VERSION: $version"
        echo "BUILDNAME: $buildname"
        echo "BUILD_SHA: $sha"
      shell: bash

    - name: Download cygwin Installer
      run: curl --output c:/setup-x86_64.exe https://cygwin.com/setup-x86_64.exe

    - name: Download OSGeo4W Installer
      run: curl --output c:/osgeo4w-setup.exe http://ftp.osuosl.org/pub/osgeo/download/osgeo4w/osgeo4w-setup-v2.exe

    - name: Download Ninja
      run: curl --location-trusted --output c:/ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip

    - name: Installing cygwin
      run: ms-windows/osgeo4w/runasadmin.ps1 c:/setup-x86_64.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/temp/cygwin -P "bison,flex,git,poppler,doxygen,unzip"
      shell: powershell

    - name: Installing OSGeo4W
      run: ms-windows/osgeo4w/runasadmin.ps1 c:/osgeo4w-setup.exe --autoaccept --advanced --arch $env:OSGEO4W_ARCH --quiet-mode --upgrade-also --root $env:OSGEO4W_ROOT --only-site -s http://ftp.osuosl.org/pub/osgeo/download/osgeo4w/v2 -l c:/temp/osgeo4w -P $env:OSGEO4W_DEPS -P python3-clcache -P qt5-devel -P python3-devel -P grass
      shell: powershell

    - name: Clear package caches
      run: |
        rmdir /s /q c:\temp\cygwin
        rmdir /s /q c:\temp\osgeo4w
      shell: cmd

    - name: Extracting Ninja
      run: c:/cygwin/bin/unzip -o c:/ninja.zip -d $env:OSGEO4W_ROOT/bin

    - name: Display tool versions
      run: |
        set PATH=%OSGEO4W_ROOT%\bin;%ProgramFiles%\CMake\bin;%PATH%
        dir $env:OSGEO4W_ROOT\bin /a
        cmake --version
        ctest --version
        ninja --version
      shell: cmd
      
    - name: Building QGIS
      run: |
        echo on
        set PATH=c:\cygwin\bin;%OSGEO4W_ROOT%\bin;%ProgramFiles%\CMake\bin;%PATH%
        cd ms-windows/osgeo4w
        type nul> skippackage
        set OSGEO4W_CXXFLAGS=/MD /MP /Od /D NDEBUG
        package-nightly.cmd %VERSION% %BINARY% %OSGEO4W_PKG% %OSGEO4W_ARCH% %BUILD_SHA%
      shell: cmd
                    
