name: build-on-windows

on:
  workflow_dispatch:

env:
  LR: release-3_12
  LTR: release-3_10
  Agent.Source.Git.ShallowFetchDepth: 120
  
jobs:
  OSGeo4W:
    strategy:
      matrix:
        config:
          - { platform: x86, cxx: "C:/OSGeo4W/bin/clcache.bat", cc: "C:/OSGeo4W/bin/clcache.bat", osgeo4w_root: "C:/OSGeo4W", osgeo4w_arch: x86, cl_cache_dir: "c:/clcache-x86" }
          - { platform: x64, cxx: "C:/OSGeo4W64/bin/clcache.bat", cc: "C:/OSGeo4W64/bin/clcache.bat", osgeo4w_root: "C:/OSGeo4W64", osgeo4w_arch: x86_64, cl_cache_dir: "c:/clcache-x86_64" }
      max-parallel: 4
    runs-on: windows-2019
    timeout-minutes: 360
    
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      OSGEO4W_ROOT: ${{ matrix.config.osgeo4w_root }}
      OSGEO4W_ARCH: ${{ matrix.config.osgeo4w_arch }}
      CLCACHE_DIR: ${{ matrix.config.cl_cache_dir }}
      PLATFORM: ${{ matrix.config.platform }}
      
    steps:
    - name: Checkout QGIS repo
      uses: actions/checkout@v4
      with:
        repository: qgis/QGIS

    - name: Setup build variables
      run: |
        if [ "$BUILD_REASON" = "PullRequest" ]; then
          branch=$SYSTEM_PULLREQUEST_TARGETBRANCH
          pr=$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
        else
          branch=$BUILD_SOURCEBRANCHNAME
        fi

        echo "BRANCH: ${branch}"
        echo "PR: ${pr}"
        echo "LR: ${LR}"
        echo "LTR: ${LTR}"

        case "${branch}" in
        "${LTR}")
          OSGEO4W_PKG=qgis-ltr-dev
          OSGEO4W_DEPS=qgis-ltr-dev-deps
          ;;
        "${LR}")
          OSGEO4W_PKG=qgis-rel-dev
          OSGEO4W_DEPS=qgis-rel-dev-deps
          ;;
        *)
          OSGEO4W_PKG=qgis-dev
          OSGEO4W_DEPS=qgis-dev-deps
          ;;
        esac

        target=Experimental
        major=$(sed -ne 's/^SET(CPACK_PACKAGE_VERSION_MAJOR "\([0-9]*\)")\s*$/\1/ip' CMakeLists.txt)
        minor=$(sed -ne 's/^SET(CPACK_PACKAGE_VERSION_MINOR "\([0-9]*\)")\s*$/\1/ip' CMakeLists.txt)
        patch=$(sed -ne 's/^SET(CPACK_PACKAGE_VERSION_PATCH "\([0-9]*\)")\s*$/\1/ip' CMakeLists.txt)
        binary=1

        version=$major.$minor.$patch
        sha="${BUILD_SOURCEVERSION:0:10}"

        if [ "$BUILD_REASON" = "PullRequest" ]; then
          buildname="PR $pr / $branch ($BUILD_BUILDID) ($sha) ($OSGEO4W_PKG $target $OSGEO4W_ARCH)"   # no colons allowed here
        else
          buildname="$OSGEO4W_PKG-$version-$sha-$target-VC14-$OSGEO4W_ARCH"
        fi

        echo "TARGET=$target" >> ${GITHUB_ENV}
        echo "OSGEO4W_PKG=$OSGEO4W_PKG" >> ${GITHUB_ENV}
        echo "OSGEO4W_DEPS=$OSGEO4W_DEPS" >> ${GITHUB_ENV}
        echo "MAJOR=$major" >> ${GITHUB_ENV}
        echo "MINOR=$minor" >> ${GITHUB_ENV}
        echo "PATCH=$patch" >> ${GITHUB_ENV}
        echo "BINARY=$binary" >> ${GITHUB_ENV}
        echo "VERSION=$version" >> ${GITHUB_ENV}
        echo "BUILDNAME=$buildname" >> ${GITHUB_ENV}
      shell: bash

    - name: Download cygwin Installer
      run: curl --output c:/setup-x86.exe https://cygwin.com/setup-x86.exe

    - name: Download OSGeo4W Installer
      run: curl --output c:/osgeo4w-setup.exe http://ftp.osuosl.org/pub/osgeo/download/osgeo4w/osgeo4w-setup-%OSGEO4W_ARCH%.exe

    - name: Download Ninja
      run: curl --location-trusted --output c:/ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip

    - name: Installing cygwin
      run: ms-windows/osgeo4w/runasadmin.ps1 c:/setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/temp/cygwin -P "bison,flex,git,poppler,doxygen,unzip"
      shell: powershell

    - name: Installing OSGeo4W
      run: ms-windows/osgeo4w/runasadmin.ps1 c:/osgeo4w-setup.exe --autoaccept --advanced --arch $env:OSGEO4W_ARCH --quiet-mode --upgrade-also --root $env:OSGEO4W_ROOT --only-site -s http://ftp.osuosl.org/pub/osgeo/download/osgeo4w -l c:/temp/osgeo4w -P $env:OSGEO4W_DEPS -P python3-clcache
      shell: powershell

    - name: Clear package caches
      run: |
        rmdir /s /q c:/temp/cygwin
        rmdir /s /q c:/temp/osgeo4w

    - name: Extracting Ninja
      run: c:/cygwin/bin/unzip -o c:/ninja.zip -d %OSGEO4W_ROOT%/bin

    - name: Display tool versions
      run: |
        PATH %OSGEO4W_ROOT%/bin;%ProgramFiles%/CMake/bin;%PATH%
        cmake --version
        ctest --version
        ninja --version

    - name: Building QGIS
      run: |
        echo on
        PATH c:/cygwin/bin;%OSGEO4W_ROOT%/bin;%PATH%
        cd ms-windows/osgeo4w
        touch skippackage
        set OSGEO4W_CXXFLAGS=/MD /MP /Od /D NDEBUG
        package-nightly.cmd %VERSION% %BINARY% %OSGEO4W_PKG% %OSGEO4W_ARCH% %BUILD_SOURCEVERSION:~0,10%
                    
