name: osgeo4w_qgis-ltr-3.34.7-2

on:
  workflow_dispatch:

env:
  LR: release-3_12
  LTR: release-3_10
  
jobs:
  OSGeo4W:
    strategy:
      max-parallel: 4
    runs-on: windows-2019
    timeout-minutes: 360
    
    env:
      OSGEO4W_ROOT: C:\OSGeo4W64
      OSGEO4W_ARCH: x86_64
      CLCACHE_DIR: c:\clcache-x86_64
      PLATFORM: x64
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up the working directory
      run: |
        mkdir C:\cygwin
        mkdir C:\OSGeo4W64

    - name: Download cygwin Installer
      run: curl --output c:/setup-x86_64.exe https://cygwin.com/setup-x86_64.exe

    - name: Download OSGeo4W V2 Installer
      run: curl --output c:/osgeo4w-setup.exe http://ftp.osuosl.org/pub/osgeo/download/osgeo4w/osgeo4w-setup-v2.exe
      
    - name: Download Ninja
      run: curl --location-trusted --output c:/ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip

    - name: Installing cygwin
      run: ms-windows/osgeo4w/runasadmin.ps1 c:/setup-x86_64.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/temp/cygwin -P "bison,git,flex,poppler,doxygen,unzip"
      shell: powershell

    - name: Installing OSGeo4W V2
      run: >
        ms-windows/osgeo4w/runasadmin.ps1 c:/osgeo4w-setup.exe --autoaccept --advanced --arch $env:OSGEO4W_ARCH 
        --quiet-mode --upgrade-also --root $env:OSGEO4W_ROOT --only-site 
        -s https://download.osgeo.org/osgeo4w/v2/snapshots/20240620-200233 -l c:/temp/osgeo4w 
        -P qgis-ltr -P qgis-ltr-pdb -P qgis-ltr-common -P qgis-ltr-deps -P qgis-ltr-devel -P qgis-ltr-grass-plugin
        -P python3-core -P qt5-devel -P python3-devel -P grass -P python3-pyqt5 -P python3-pyqt5-sip
        -P qt5-libs -P zstd-devel -P pdal-libs -P pdal -P pdal-devel -P draco -P draco-devel -P proj-devel -P curl-devel
        -P libtiff-devel -P qscintilla -P python3-qscintilla -P qscintilla-devel
      shell: powershell

    - name: Clear package caches
      run: |
        rmdir /s /q c:\temp\cygwin
        rmdir /s /q c:\temp\osgeo4w
      shell: cmd

    - name: Extracting Ninja
      run: c:/cygwin/bin/unzip -o c:/ninja.zip -d $env:OSGEO4W_ROOT/bin

    - name: Display tool versions
      run: |
        set PATH=%OSGEO4W_ROOT%\bin;%ProgramFiles%\CMake\bin;%PATH%
        dir . /a
        dir c:\ /a
        dir c:\OSGeo4W64 /a
        dir c:\OSGeo4W64\bin /a
        dir c:\OSGeo4W64\apps /a
        dir c:\OSGeo4W64\etc\ini /a
        cmake --version
        ctest --version
        ninja --version
      shell: cmd

    - name: pack cygwin & OSGeo4W64
      run: |
        7z a build-cygwin-devel-x86_64.zip c:\cygwin
        7z a build-OSGeo4W64-devel-x86_64.zip c:\OSGeo4W64
      
    - name: set release date
      run: |
        echo "RELEASE_DATE=$(date +%Y%m%d-%H%M%s)" >> ${GITHUB_ENV}
      shell: bash

    - name: Release cygwin
      uses: softprops/action-gh-release@v1
      with:
        name: build-cygwin-devel-x86_64-3.34.7-2
        tag_name: ${{ env.RELEASE_DATE }}
        files: build-cygwin-devel-x86_64.zip
        
    - name: Release OSGeo4W64
      uses: softprops/action-gh-release@v1
      with:
        name: build-OSGeo4W64-devel-x86_64-3.34.7-2
        tag_name: ${{ env.RELEASE_DATE }}
        files: build-OSGeo4W64-devel-x86_64.zip
                    
