name: get_cygwin

on:
  workflow_dispatch:
    inputs:
      snapshots:
        description: 'snapshots to build'
        required: true
        default: '20241127-081725'

env:
  LTR: release-3_34
  
jobs:
  OSGeo4W:
    strategy:
      max-parallel: 4
    runs-on: windows-2019
    timeout-minutes: 360
    
    env:
      OSGEO4W_ROOT: C:\OSGeo4W64
      OSGEO4W_ARCH: x86_64
      CLCACHE_DIR: c:\clcache-x86_64
      PLATFORM: x64
      SNAPSHOTS_BUILD: ${{ github.event.inputs.snapshots }}
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up the working directory
      run: |
        mkdir C:\cygwin
        mkdir C:\OSGeo4W64

    - name: Get QGIS Version
      run: |
        curl --output ./qgis-ltr-setup.hint https://download.osgeo.org/osgeo4w/v2/snapshots/${{ github.event.inputs.snapshots }}/x86_64/release/qgis/qgis-ltr/setup.hint
        echo "RELEASE_QGIS_VERSION=$(awk -F: '$1 ~ /curr/ {print $2}' ./qgis-ltr-setup.hint | awk '$1=$1')" >> ${GITHUB_ENV}
      shell: bash

    - name: Download cygwin Installer
      run: curl --output c:/setup-x86_64.exe https://cygwin.com/setup-x86_64.exe

    - name: Download OSGeo4W V2 Installer
      run: curl --output c:/osgeo4w-setup.exe http://ftp.osuosl.org/pub/osgeo/download/osgeo4w/osgeo4w-setup-v2.exe
      
    - name: Download Ninja
      run: curl --location-trusted --output c:/ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip

    - name: Installing cygwin
      run: ms-windows/osgeo4w/runasadmin.ps1 c:/setup-x86_64.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/temp/cygwin -P "bison,git,flex,poppler,doxygen,unzip"
      shell: powershell

    - name: Clear package caches
      run: |
        rmdir /s /q c:\temp\cygwin
      shell: cmd

    - name: Extracting Ninja
      run: c:/cygwin/bin/unzip -o c:/ninja.zip -d $env:OSGEO4W_ROOT/bin

    - name: pack cygwin & OSGeo4W64
      run: |
        7z a build-cygwin-devel-x86_64-${{ env.RELEASE_QGIS_VERSION }}.zip c:\cygwin
      
    - name: set release date
      run: |
        echo "RELEASE_DATE=$(date +%Y%m%d-%H%M%s)" >> ${GITHUB_ENV}
        RELBRANCH=$(echo "${{ env.RELEASE_QGIS_VERSION }}" | awk -F- '{print $1}')
        echo "https://github.com/qgis/QGIS/archive/refs/tags/final-$RELBRANCH.zip" > ${{ github.workspace }}-SRC.txt
      shell: bash

    - name: Release cygwin
      uses: softprops/action-gh-release@v2
      with:
        name: build-cygwin-devel-x86_64-${{ env.RELEASE_QGIS_VERSION }}
        tag_name: ${{ env.RELEASE_DATE }}
        files: build-cygwin-devel-x86_64-${{ env.RELEASE_QGIS_VERSION }}.zip
        body_path: ${{ github.workspace }}-SRC.txt
