name: CI-release-build

on:
    workflow_dispatch:

jobs:
  create_package:
    runs-on: ubuntu-20.04

    steps:
      - name: init env
        shell: bash
        run: |
          pwd
          mkdir -p ./artifact

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date +%Y%m%d-%H%M%s)" >> ${GITHUB_ENV}

      - name: download release artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: mingw64.yml
          name: QGIS for Windows 64bit
          path: ./artifact
          repo: qgis/QGIS

      - name: download debug symbols
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: mingw64.yml
          name: QGIS for Windows 64bit Debug Symbols
          path: ./artifact
          repo: qgis/QGIS
          
      - name: Display structure of downloaded files
        run: ls -al
        working-directory: ./artifact

      - name: pack downloaded files
        run: zip -r QGIS_Windows_x64.zip ./artifact

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: QGIS_Windows_x64
          tag_name: ${{ env.RELEASE_DATE }}
          files: QGIS_Windows_x64.zip
