name: Build QGIS By Vcpkg

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y zip git flex bison build-essential ca-certificates ccache cmake autoconf autoconf-archive automake libtool

      - name: 🐩 Install CMake and Ninja
        uses: lukka/get-cmake@7bfc9baacbbdcb5e37957ad05c3546b3e222be3c # latest
        with:
          # Pin to specific version to avoid rebuilding too often
          # Also helps to avoid spurious build failures like https://github.com/qgis/QGIS/pull/47098
          cmakeVersion: 3.30.4

      - name: Install VCPKG_ROOT
        run: |
          export VCPKG_ROOT=$HOME/.vcpkg
          wget https://aka.ms/vcpkg-init.sh -O /tmp/vcpkg-init.sh
          . /tmp/vcpkg-init.sh
          echo "VCPKG_ROOT=$VCPKG_ROOT" >> $GITHUB_ENV
          echo "$VCPKG_ROOT" >> $GITHUB_PATH

      - name: clone QGIS repo
        uses: actions/checkout@v6
        with:
          repository: qgis/QGIS
          path: qgis

      - name: Configure QGIS
        run: |
          echo "VCPKG_ROOT: ${VCPKG_ROOT}"
          cmake -S ./qgis \
            -B ./build-x64-linux \
            -GNinja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DWITH_VCPKG=ON \
            -DWITH_BINDINGS=ON \
            -DWITH_QTWEBENGINE=OFF \
            -DWITH_ORACLE=OFF \
            -DWITH_GEOGRAPHICLIB=OFF \
            -DWITH_SFCGAL=ON \
            -DWITH_PROJ_DATA=ON \
            -DENABLE_TESTS=OFF \
            -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic-release \
            -DVCPKG_HOST_TRIPLET=x64-linux-dynamic-release

      - name: Build QGIS
        run: |
          cmake --build ./build-x64-linux
          ls -la ./
          ls -la ./qgis
          ls -la ./build-x64-linux
          ls -la ./build-x64-linux/output
          ls -la ./build-x64-linux/vcpkg_installed/x64-linux-dynamic-release

      - name: Set release date
        run: |
          echo "RELEASE_DATE=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Pack output
        run: |
          zip -r -y QGIS-output-${{ env.RELEASE_DATE }}.zip ./build-x64-linux/output
          zip -r -y QGIS-vcpkg_installed-${{ env.RELEASE_DATE }}.zip ./build-x64-linux/vcpkg_installed/x64-linux-dynamic-release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: vcpkg-qgis-${{ env.RELEASE_DATE }}
          name: vcpkg-qgis-${{ env.RELEASE_DATE }}
          body: |
            QGIS vcpkg build
          files: |
            QGIS-output-${{ env.RELEASE_DATE }}.zip
            QGIS-vcpkg_installed-${{ env.RELEASE_DATE }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}